AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spark API - com.demo::spark-cloud
Resources:
  SparkCloudFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/spark-cloud-1.0.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 40
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SparkCloudApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: SparkCloudApi
